"""empty message

Revision ID: 2a696c239f8
Revises: None
Create Date: 2014-09-17 14:41:02.951264

"""

# revision identifiers, used by Alembic.
revision = '2a696c239f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)
    op.create_table('tracklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracklists_name'), 'tracklists', ['name'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('bio', sa.UnicodeText(), nullable=True),
    sa.Column('email', sa.Unicode(length=256), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=True)
    op.create_index(op.f('ix_members_permissions'), 'members', ['permissions'], unique=False)
    op.create_table('playlists',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('local_id', 'owner_id')
    )
    op.create_table('albums',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('local_id', 'owner_id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('location', sa.Unicode(), nullable=True),
    sa.Column('stream', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('stream')
    )
    op.create_index(op.f('ix_tracks_name'), 'tracks', ['name'], unique=False)
    op.create_table('trackpositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('tracklist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['tracklist_id'], ['tracklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackpositions_track_id'), 'trackpositions', ['track_id'], unique=False)
    op.create_index(op.f('ix_trackpositions_tracklist_id'), 'trackpositions', ['tracklist_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackpositions_tracklist_id'), table_name='trackpositions')
    op.drop_index(op.f('ix_trackpositions_track_id'), table_name='trackpositions')
    op.drop_table('trackpositions')
    op.drop_index(op.f('ix_tracks_name'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('albums')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_members_permissions'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_tracklists_name'), table_name='tracklists')
    op.drop_table('tracklists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    ### end Alembic commands ###
