"""empty message

Revision ID: 4b3a3cf21fa
Revises: None
Create Date: 2014-09-15 22:31:29.856070

"""

# revision identifiers, used by Alembic.
revision = '4b3a3cf21fa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
